export const REGISTER_SUCCESS = "REGISTER_SUCCES";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const POST_ACTION_SUCCESS = "POST_ACTION_SUCCESS";
export const POST_ACTION_FAIL = "POST_ACTION_FILE";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
